# Generated by Django 5.2.7 on 2025-08-30

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customerleads', '0007_remove_lead_city_remove_lead_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_deleted', 'Lead Deleted'), ('lead_converted', 'Lead Converted'), ('call_made', 'Call Made'), ('delivery_created', 'Delivery Created'), ('delivery_updated', 'Delivery Updated'), ('delivery_assigned', 'Delivery Assigned'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('client_created', 'Client Created'), ('settings_changed', 'Settings Changed'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_created_idx'), models.Index(fields=['action', '-created_at'], name='action_created_idx')],
            },
        ),
    ]
