# Generated by Django 5.2.7 on 2026-08-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerleads', '0008_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='customerlea_user_id_ba7c43_idx',
            old_name='user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='customerlea_action_4120ac_idx',
            old_name='action_created_idx',
        ),
    ]
